### ISSUE TITLE
Error running on M1 chip

### ISSUE THREAD

**Issue by jsan4christ** [blab/ncov-africa#1]
Dear NS Team,

 Please assist with this error,

$ nextstrain build . -j 4 -n -p --configfile ../ncov-africa/builds.yaml
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Error: no Snakefile found, tried Snakefile, snakefile, workflow/Snakefile, workflow/snakefile.

Thanks

**Comment by cassiawag** [comment]
Hi @jsan4christ, sorry for the delay in getting back to you, I'm just seeing this now. Are you still running into this error?
Best,
Cassia

**Comment by huddlej** [comment]
@jsan4christ and I chatted today at office hours and he said this issue was resolved by running the workflow with a profile instead of the configfile.
